#!/bin/bash
# pre for scduply + windows 7/8/8.1 + vss

function remove_shadow_server {
	vssadmin delete shadows  /Shadow=$1 /Quiet > /dev/null
}

function remove_shadow_workstation {
# remove_shadow [ssid]
	cd "$vss_tool_path"
	./vshadow.exe -dx=$ShadowSetID 
}

rm -f /vsshadow/*
[[ "$win_os_type" == "server" ]] && remove_shadow_server || remove_shadow_workstation