#!/bin/bash
# work with shadowcopy in cygwin for scduply + windows 7/8/8.1/10
# autor: Elias Arkhipov
# mail: ai@c-mit.ru

unset shadowid
unset shadowvolume

function diskletter {
	local _diskletter=`echo "$1"|egrep -o "/[a-z]/"`
	echo ${_diskletter////}
}

echo $SOURCE|grep "cygdrive" && {
	. scwin_vss create $(diskletter "$SOURCE")
	SOURCE=${SOURCE//cygdrive/vsshadow}
}

echo "updated SOURCE=$SOURCE"